### PR TITLE
Workaround for broken QT dialogs for MacOSX Monterrey with QT6.2.2

### PR DESCRIPTION
**Pull request by phunkyfish**
@kambala-decapitator can you take a look?

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
In your current implementation you're trying to show the dialog twice on Monterey which doesn't seem right.

Instead, make the flags a variable that you'd update on Monterey, here's an example for the first case:

```c++
    auto flags = QFileDialog::ShowDirsOnly | QFileDialog::DontResolveSymlinks;
#ifdef Q_OS_MAC
     if (QOperatingSystemVersion::current().majorVersion() >= 12)
         flags |= QFileDialog::DontUseNativeDialog;
#endif

    saveDir = QFileDialog::getExistingDirectory(this,
                tr("Directory to store image file"),
                 saveDir,
                 flags);
```

**Comment by phunkyfish** [comment]
Gotcha, makes sense.

**Comment by phunkyfish** [comment]
Should be good now @kambala-decapitator

**Review by kambala-decapitator — APPROVED** [review]
Later this commit can be simply reverted

**Review by chewitt — APPROVED** [review]

**Pull request merged**
